name: fufuland

services:
  tunnel:
    image: ghcr.io/playit-cloud/playit-agent:latest
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    restart: 'no'

  server:
    profiles:
      - server
    # network_mode: host
    cpu_shares: 4096
    restart: 'no'
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-linux}
        MEMORY_ALLOCATION: ${MEMORY_ALLOCATION:-16G}
        MODPACK_ARCHIVE: ${MODPACK_ARCHIVE:-the-modpack-1.1.0.mrpack}
    container_name: fufuland-server
    ports:
      - '25565:25565/tcp'
      - '25565:25565/udp'
    volumes:
      - mc-data:/opt/minecraft/mc
      - ./server.properties:/opt/minecraft/mc/server.properties
    env_file:
      - .env
    healthcheck:
      test:
        ['CMD', 'mc-monitor', 'status', '-host', '0.0.0.0', '-port', '25565']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  backup:
    build:
      context: .
      dockerfile: backup.dockerfile
      args:
        OPERATION: write
    environment:
      - OPERATION=write
    profiles:
      - backup
    volumes:
      - mc-bias:/data:ro # same named volume, read-only
      - ./.backups:/backup # host folder that rclone will read from
      - ./scripts/backup.sh:/script/backup.sh:ro
    restart: 'no'
    network_mode: host
    dns:
      - 127.0.0.1

  restore:
    network_mode: host
    dns:
      - 127.0.0.1
    build:
      context: .
      dockerfile: backup.dockerfile
      args:
        OPERATION: read
    environment:
      - OPERATION=read
    profiles:
      - restore
    volumes:
      - mc-bias:/data # restore target
      - ./.backups:/backup:ro # host backups folder, read-only
      - ./scripts/backup.sh:/script/backup.sh:ro
    restart: 'no'

  serverpack:
    profiles:
      - serverpack
    network_mode: host
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: serverpack.Dockerfile
    container_name: fufuland-serverpack
    ports:
      - '25566:25566/tcp'
      - '25566:25566/udp'
    volumes:
      - mc-serverpack:/data
      - ./eula.txt:/data/eula.txt
      - ./server.properties:/data/server.properties
      - ./server-icon.png:/data/server-icon.png
      - ./user_jvm_args.txt:/data/user_jvm_args.txt
      - ./scripts/start-server.sh:/data/start-server.sh
      - ./server-1.16.5.jar:/data/server-1.16.5.jar
    restart: 'no'

  bias:
    network_mode: host
    dns:
      - 127.0.0.1
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - '25564:25564'
    environment:
      EULA: 'TRUE'
      TYPE: 'MODRINTH'
      INIT_MEMORY: '3G'
      MAX_MEMORY: '12G'
      MODRINTH_MODPACK: '/data/modpacks/bias-processed.mrpack'
      SKIP_SERVER_PROPERTIES: 'TRUE'
      SERVER_PORT: '25564'
    volumes:
      - 'mc-bias:/data'
      - ./server.properties:/data/server.properties
      - ./server-icon.png:/data/server-icon.png
      - ./bias-processed.mrpack:/data/modpacks/bias-processed.mrpack
    env_file:
      - .env

volumes:
  mc-data:
  mc-serverpack:
  mc-bias:
