name: fufuland

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    platform: linux/amd64
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      server:
        condition: service_healthy

  server:
    cpu_shares: 4096
    restart: no
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fufuland-server
    ports:
      - 25565:25565
    volumes:
      - mc-data:/opt/minecraft/mc
      - ./server.properties:/opt/minecraft/mc/server.properties
    environment:
      - MEMORY=8G
    healthcheck:
      test: ["CMD", "mc-monitor", "status",
             "-host", "0.0.0.0", "-port", "25565"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  backup:
    image: busybox:stable
    profiles:
      - backup
    entrypoint: >
      sh -c '
      ARCHIVE="mc-data-$(date +%Y-%m-%d-%H-%M-%S).tar.gz" &&
      echo "Starting backup to $$ARCHIVE..." &&
      tar -czvf /backup/$$ARCHIVE -C /src . &&
      echo "Backup completed! Archive stored at /backup/$$ARCHIVE" '
    volumes:
      - mc-data:/src:ro           # same named volume, read-only
      - ./.backups:/backup         # host folder that rclone will read from
    depends_on:
      - server

volumes:
  mc-data:
