name: fufuland

services:
  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    platform: linux/amd64
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fufuland-server
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/opt/minecraft/mc
      - ./server.properties:/opt/minecraft/server.properties
    environment:
      - MEMORY=8G
    restart: no
    stdin_open: true
    tty: true

volumes:
  mc-data:
