name: fufuland

services:
  tunnel:
    image: ghcr.io/playit-cloud/playit-agent:latest
    network_mode: host
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      server:
        condition: service_healthy

  server:
    network_mode: host
    cpu_shares: 4096
    restart: no
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: linux
    container_name: fufuland-server
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    volumes:
      - mc-data:/opt/minecraft/mc
      - ./server.properties:/opt/minecraft/mc/server.properties
    environment:
      - MEMORY_ALLOCATION=10G
    healthcheck:
      test: ["CMD", "mc-monitor", "status",
             "-host", "0.0.0.0", "-port", "25565"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  backup:
    build:
      context: .
      dockerfile: backup.dockerfile
      args:
        OPERATION: write
    environment:
      - OPERATION=write
    profiles:
      - backup
    volumes:
      - mc-data:/data:ro           # same named volume, read-only
      - ./.backups:/backup         # host folder that rclone will read from
      - ./scripts/backup.sh:/script/backup.sh:ro
    restart: "no"

  restore:
    build:
      context: .
      dockerfile: backup.dockerfile
      args:
        OPERATION: read
    environment:
      - OPERATION=read
    profiles:
      - restore
    volumes:
      - mc-data:/data          # restore target
      - ./.backups:/backup:ro # host backups folder, read-only  
      - ./scripts/backup.sh:/script/backup.sh:ro
    restart: "no"

volumes:
  mc-data:
