name: fufuland

services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fufuland-mc
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data/mc
    environment:
      - MEMORY=4G
      - EULA=TRUE
      - TYPE=CUSTOM
      - CUSTOM_SERVER=/data/fabric-server-mc.1.21.5-loader.0.16.14-launcher.1.0.3.jar
    restart: no
    stdin_open: true
    tty: true

volumes:
  mc-data:
