#Minecraft server properties
#Sun Feb 22 13:26:47 UTC 2026
accepts-transfers=false
allow-cheats=true
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=hard
enable-code-of-conduct=false
enable-command-block=true
enable-jmx-monitoring=false
enable-lan-visibility=true
enable-query=true
enable-rcon=true
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=4
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=asetland
level-seed=875930400000
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=1ExjEJLJC5JiVUzbG7QPkFscqV11L6HHA0fjsmYd
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=5
max-threads=0
max-tick-time=60000
max-world-size=29999984
motd=sesbian lex
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=30
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=3cc486bbdc874e7f63f8e514
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=0.0.0.0
server-port=25564
simulation-distance=8
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=32
white-list=false
